plugins:
    - ace-editor
    - ant
    - antisamy-markup-formatter
    - bouncycastle-api
    - branch-api
    - build-timeout
    - cloudbees-folder
    - credentials-binding
    - credentials
    - display-url-api
    - durable-task
    - email-ext
    - external-monitor-job
    - git-client
    - git-server
    - git
    - github-api
    - github-branch-source
    - github-organization-folder
    - github
    - gradle
    - handlebars
    - icon-shim
    - jquery-detached
    - junit
    - ldap
    - mailer
    - mapdb-api
    - matrix-auth
    - matrix-project
    - momentjs
    - pam-auth
    - pipeline-build-step
    - pipeline-graph-analysis
    - pipeline-input-step
    - pipeline-milestone-step
    - pipeline-rest-api
    - pipeline-stage-step
    - pipeline-stage-view
    - plain-credentials
    - resource-disposer
    - scm-api
    - script-security
    - ssh-credentials
    - ssh-slaves
    - structs
    - subversion
    - swarm
    - timestamper
    - token-macro
    - windows-slaves
    - workflow-aggregator
    - workflow-api
    - workflow-basic-steps
    - workflow-cps-global-lib
    - workflow-cps
    - workflow-durable-task-step
    - workflow-job
    - workflow-multibranch
    - workflow-scm-step
    - workflow-step-api
    - workflow-support
    - ws-cleanup

